### ISSUE TITLE
Improve add-on testing experience with existing cluster

### ISSUE THREAD

**Issue by gyuho** [aws/aws-k8s-tester#123]
Cluster creation is expensive taking >20-min.

Create cluster once.
Run add-on tests.
Clean up add-on tests resources.
Run more add-on tests.
Clean up add-on tests resources.
(Optional) delete cluster.

**Comment by ellistarn** [comment]
One possible user experience

A few key points
- This YAML serializes to a go struct, which represents the AKT configuration
- All keys are go pointers, and if omitted, it's effectively "disabled"
- Enables users to attach to existing test or cluster cluster
  - i.e., if an AKT cluster already exists, user can change addons config, and AKT will only apply the changes
  - A user developing AKT can make code changes to AKT and reapply the same config, which will simply apply again (if metadata.name is the same)
  - Each addon's installation and deletion must be idempotent
- There is a delete-cluster="false" option, so that addons can be uninstalled but the cluster remains

```      
AKT_CONFIG_FILE="" # User can either provide config file or yaml in line. If file not provided, AKT creates one to manage state inside "status"
AKT_CONFIG_YAML="
metadata: 
    name: cluster-name # Test name prefix, if not provided, generates name for test
spec: 
    eks: # Cluster creation fields
        region: us-west-2
        parititon: aws
    s3: 
        bucketName: # if not provided, creates a new bucket
    mng:
        groups: 
            - name: foo
              image-id-ssm-parameter
              instance-types: 
                - c5.xlarge
    clusterAutoscaler: {} # Enabled but uses defaults
    metricsServer: {} # Enabled but uses defaults
    irsa: 
        repositoryAccountId: 607362164682
        repositoryAccountName: aws/aws-k8s-tester
        repositoryImageTag: latest
status: {} # AKT maintains its state here
"
aws-k8s-tester eks create # Generates resources in AKT_CONFIG
aws-k8s-tester eks delete # Detects necessary info from yaml file 
```
